# Generated by Django 6.0.2 on 2026-02-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('invoice', 'reference'), name='uniq_receipt_reference_per_invoice'),
        ),
    ]
