# Generated by Django 6.0.2 on 2026-02-17 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(choices=[('DUTY', 'Duty Zone'), ('FREE', 'Free Zone'), ('EXPORT', 'Export')], max_length=10)),
                ('file_number', models.CharField(max_length=80, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bl_awb', models.CharField(blank=True, default='', max_length=120)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('container_40ft', models.PositiveIntegerField(default=0)),
                ('container_20ft', models.PositiveIntegerField(default=0)),
                ('others', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('container_number', models.CharField(blank=True, default='', max_length=120)),
                ('transit_days', models.PositiveIntegerField(blank=True, null=True)),
                ('duty_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='clients.client')),
            ],
        ),
    ]
