# Generated by Django 6.0.2 on 2026-03-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="port",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="job",
            name="vessel",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
