# Generated by Django 6.0.2 on 2026-02-17 16:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('RECEIPT', 'Receipt')], max_length=20)),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('source_id', models.UUIDField(unique=True)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('invoice_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['job_id', 'event_date'], name='ledger_ledg_job_id_5bf7f7_idx'), models.Index(fields=['invoice_id', 'event_date'], name='ledger_ledg_invoice_5e1c41_idx'), models.Index(fields=['entry_type', 'event_date'], name='ledger_ledg_entry_t_47a16a_idx')],
            },
        ),
    ]
