# Generated by Django 6.0.2 on 2026-02-17 17:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('JOB', 'Job'), ('INVOICE', 'Invoice'), ('RECEIPT', 'Receipt')], max_length=20)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('invoice_id', models.UUIDField(blank=True, null=True)),
                ('receipt_id', models.UUIDField(blank=True, null=True)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('storage_provider', models.CharField(default='cloudinary', max_length=30)),
                ('storage_key', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['job_id'], name='documents_d_job_id_698265_idx'), models.Index(fields=['invoice_id'], name='documents_d_invoice_ea6f0b_idx'), models.Index(fields=['receipt_id'], name='documents_d_receipt_ed8dba_idx')],
            },
        ),
    ]
