# Generated by Django 6.0.2 on 2026-02-17 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(choices=[('DUTY', 'Duty Zone'), ('FREE', 'Free Zone'), ('EXPORT', 'Export')], max_length=10)),
                ('key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['zone', 'sort_order'],
                'unique_together': {('zone', 'key')},
            },
        ),
        migrations.CreateModel(
            name='JobMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='jobs.job')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracking.milestonetemplate')),
            ],
            options={
                'ordering': ['template__sort_order'],
                'unique_together': {('job', 'template')},
            },
        ),
    ]
