# Generated by Django 6.0.2 on 2026-03-12 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


def migrate_completed_milestones_to_tracker_entries(apps, schema_editor):
    JobMilestone = apps.get_model("tracking", "JobMilestone")
    TrackerEntry = apps.get_model("tracking", "TrackerEntry")

    for milestone in JobMilestone.objects.select_related("job", "template").iterator():
        if milestone.status != "DONE" and milestone.date is None:
            continue

        TrackerEntry.objects.create(
            id=uuid.uuid4(),
            job_id=milestone.job_id,
            entry_date=milestone.date or milestone.job.created_at.date(),
            progress_report=milestone.template.label,
            next_step="",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ("entry_date", models.DateField()),
                ("progress_report", models.TextField()),
                ("next_step", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name="tracker_entries", to="jobs.job")),
            ],
            options={
                "ordering": ["entry_date", "created_at"],
            },
        ),
        migrations.RunPython(
            migrate_completed_milestones_to_tracker_entries,
            migrations.RunPython.noop,
        ),
    ]
